export const START_QUIZ = "START_QUIZ";
export const TOGGLE_FULLSCREEN = "TOGGLE_FULLSCREEN";
export const SELECT_QUESTION = "SELECT_QUESTION";
export const SELECT_CHOICE = "SELECT_CHOICE";
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const ANSWER_QUESTION_REQUEST = "ANSWER_QUESTION_REQUEST";
export const ANSWER_QUESTION_SUCCESS = "ANSWER_QUESTION_SUCCESS";
export const RESTART_QUIZ = "RESTART_QUIZ";
