export const SELECT_QUESTION = "SELECT_QUESTION";
export const UNSELECT_QUESTION = "UNSELECT_QUESTION";
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const AUTH_STATE_CHANGED = "AUTH_STATE_CHANGED";

export const OPEN_QUESTION_FORM_DIALOG = "OPEN_QUESTION_FORM_DIALOG";
export const CLOSE_QUESTION_FORM_DIALOG = "CLOSE_QUESTION_FORM_DIALOG";

export const CREATE_QUIZ = "CREATE_QUIZ";
export const UPDATE_QUIZ = "UPDATE_QUIZ";

export const CREATE_QUESTION = "CREATE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";

export const DELETE_QUIZ = "DELETE_QUIZ";
export const DELETE_QUIZ_CONFIRMED = "DELETE_QUIZ_CONFIRMED";
export const DELETE_QUIZ_CANCELLED = "DELETE_QUIZ_CANCELLED";

export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_QUESTION_CONFIRMED = "DELETE_QUESTION_CONFIRMED";
export const DELETE_QUESTION_CANCELLED = "DELETE_QUESTION_CANCELLED";

export const RESTART_QUIZ = "RESTART_QUIZ";
export const RESTART_QUIZ_CONFIRMED = "RESTART_QUIZ_CONFIRMED";
export const RESTART_QUIZ_CANCELLED = "RESTART_QUIZ_CANCELLED";

export const EXITED_FROM_QUIZ = "EXITED_FROM_QUIZ";

export const SHARE_QUIZ_CODE = "SHARE_QUIZ_CODE";
export const SHARE_QUIZ_CODE_COMPLETED = "SHARE_QUIZ_CODE_COMPLETED";

export const LISTEN_AUTH_STATE = "LISTEN_AUTH_STATE";

export const FETCH_AUTH_USER_QUIZZES = "FETCH_AUTH_USER_QUIZZES";
export const FETCH_QUIZ = "FETCH_QUIZ";
export const FETCH_QUIZ_QUESTIONS = "FETCH_QUIZ_QUESTIONS";
